Repository MattReed-ZA/RazielRising, pull requests merged in 2022-09, with the labels that each got.

#10 🐛 Fixed pause menu transition
  Assets/Animations/Animation Controllers/Player AC.controller
  Assets/Animations/Unity Animation/CrossFade_FadeIn.anim
  Assets/Animations/Unity Animation/CrossFade_FadeOut.anim
  Assets/Animations/Unity Animation/LevelLoader.controller
  Assets/Animations/Unity Animation/LevelLoader.controller.meta
  Assets/LevelControl.cs
  Assets/LevelLoader.cs
  Assets/PauseMenuController.cs
  Assets/PlayBTN.cs
  Assets/Prefabs/LevelLoader.prefab
  Assets/Prefabs/PauseMenu.prefab
  Assets/Scenes/GameScene 1.unity
  Assets/Scenes/GameScene.unity
Labels: bug, Task, Individual Task: Matthew

#11 fixing animations again
  Assets/Animations/Animation PNGS/IDLE/New idle/idle_0000_State-1 1.png
  Assets/Animations/Animation PNGS/IDLE/New idle/idle_0000_State-1 1.png.meta
  Assets/Animations/Animation PNGS/IDLE/New idle/idle_0004_State-5.png
  Assets/Animations/Animation PNGS/IDLE/New idle/idle_0004_State-5.png.meta
  Assets/Animations/Unity Animation/Idle.anim
  Assets/Animations/Unity Animation/Jump 3.anim
  Assets/Animations/Unity Animation/Walk.anim
  Assets/Scenes/GameScene.unity
  UserSettings/EditorUserSettings.asset
Labels: bug, Individual Task: Mayur

#13 🚧 ✨ (Save & Load): Created save and load system
  Assets/Animations/Animation PNGS/BUTTONS/loadbtn.png
  Assets/Animations/Animation PNGS/BUTTONS/loadbtn.png.meta
  Assets/Animations/Animation PNGS/BUTTONS/savebtn.png
  Assets/Animations/Animation PNGS/BUTTONS/savebtn.png.meta
  Assets/Animations/Animation PNGS/BUTTONS/skip.png
  Assets/Animations/Animation PNGS/BUTTONS/skip.png.meta
  Assets/LevelLoader.cs
  Assets/PauseMenuController.cs
  Assets/PlayerController.cs
  Assets/PlayerData.cs
  Assets/PlayerData.cs.meta
  Assets/Prefabs/PauseMenu.prefab
  Assets/SaveSystem.cs
  Assets/SaveSystem.cs.meta
  Assets/Scenes/GameScene 1.unity
  Assets/Scenes/GameScene.unity
Labels: Task, Individual Task: Matthew, Chore

#15 🐛 fixed loading bug
  Assets/PlayerController.cs
  Assets/SaveSystem.cs
  UserSettings/EditorUserSettings.asset
Labels: bug, Task, Individual Task: Matthew, Chore

#16 ✨ Skip Objective feature added
  Assets/Animations/Animation PNGS/BUTTONS/skipLevel.png
  Assets/Animations/Animation PNGS/BUTTONS/skipLevel.png.meta
  Assets/LevelLoader.cs
  Assets/PauseMenuController.cs
  Assets/PlayerController.cs
  Assets/Prefabs/PauseMenu.prefab
  Assets/Scenes/GameScene 1.unity
  Assets/Scenes/GameScene.unity
  UserSettings/EditorUserSettings.asset
Labels: Task, Individual Task: Matthew, Chore
