Repository MattReed-ZA/RazielRising, pull requests merged in 2022-10, with the labels that each got.

#18 Dharshan
  .plastic/plastic.changes
  .plastic/plastic.wktree
  Assets/Instruction PNGS/Text/Projectile Bash Instructions.png
  Assets/Instruction PNGS/Text/Projectile Bash Instructions.png.meta
  Assets/PlayerController.cs
  Assets/Resources/crickets-26444.mp3
  Assets/Resources/crickets-26444.mp3.meta
  Assets/Scenes/GameScene 1.unity
  Assets/Scenes/GameScene 2.unity
  Assets/Scenes/GameScene 2.unity.meta
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Projectiles.cs
  Assets/Scripts/Projectiles.cs.meta
  Assets/Sound/Fireplace.mp3
  Assets/Sound/Fireplace.mp3.meta
  Assets/Sprites/Ability Assets/Projectile Shooter.png
  Assets/Sprites/Ability Assets/Projectile Shooter.png.meta
  Assets/Sprites/Ability Assets/Projectile.png
  Assets/Sprites/Ability Assets/Projectile.png.meta
  Assets/Sprites/Environment/Asset 39.png
  Assets/Sprites/Environment/Asset 39.png.meta
  Assets/Sprites/Environment/Asset 51.png
  Assets/Sprites/Environment/Asset 51.png.meta
  Assets/Sprites/Environment/Skulls/skull spike 1.png
  Assets/Sprites/Environment/Skulls/skull spike 1.png.meta
  Assets/Sprites/Environment/Skulls/skull spike 2.png
  Assets/Sprites/Environment/Skulls/skull spike 2.png.meta
  Assets/Sprites/Environment/Skulls/skull spike 3.png
  Assets/Sprites/Environment/Skulls/skull spike 3.png.meta
  Assets/Sprites/Environment/tree inverted.png
  Assets/Sprites/Environment/tree inverted.png.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/TagManager.asset
Labels: Task, Individual Task: Dharshan, Chore

#19 🐛 ✨ (Matthew): Checkpoint and Restart
  Assets/Animations/Animation PNGS/BUTTONS/restartbtn.png
  Assets/Animations/Animation PNGS/BUTTONS/restartbtn.png.meta
  Assets/PauseMenuController.cs
  Assets/PlayerController.cs
  Assets/Prefabs/PauseMenu.prefab
  Assets/Scenes/Level_1_Day.unity
  Assets/Scenes/Level_1_Day.unity.meta
  Assets/Scenes/Level_1_Night.unity
  Assets/Scenes/Level_1_Night.unity.meta
  Assets/Scenes/Level_2_Night.unity
  Assets/Scenes/Level_2_Night.unity.meta
  ProjectSettings/EditorBuildSettings.asset
  UserSettings/EditorUserSettings.asset
Labels: bug, Task, Individual Task: Matthew, Chore

#21 Volume slider and death screen
  Assets/GameOverScreen.cs
  Assets/GameOverScreen.cs.meta
  Assets/PlayerController.cs
  Assets/Prefabs/PauseMenu.prefab
  Assets/Scenes/Level_1_Day.unity
  Assets/Scenes/Level_1_Night.unity
  Assets/Scenes/Level_2_Night.unity
  Assets/Scenes/MenuScene.unity
  UserSettings/EditorUserSettings.asset
Labels: Task, Individual Task: Mayur

#22 decorations and day sfx
  Assets/Scenes/Level_1_Day.unity
  Assets/Scenes/Level_1_Night.unity
  Assets/Scenes/Level_2_Night.unity
  Assets/Sound/ambience.meta
  Assets/Sound/ambience/crickets-26444.mp3
  Assets/Sound/ambience/crickets-26444.mp3.meta
  Assets/Sound/ambience/mixkit-swamp-and-jungle-birds-ambience-325.mp3
  Assets/Sound/ambience/mixkit-swamp-and-jungle-birds-ambience-325.mp3.meta
  Assets/Sprites/Environment/Above ground filler/broken vase.png
  Assets/Sprites/Environment/Above ground filler/broken vase.png.meta
  UserSettings/EditorUserSettings.asset
Labels: Task, Individual Task: Mayur

#23 Mayur new branch
  Assets/Prefabs/PauseMenu.prefab
  Assets/Scenes/Level_1_Day.unity
  Assets/Scenes/Level_1_Night.unity
  Assets/Scenes/Level_2_Night.unity
  UserSettings/EditorUserSettings.asset
Labels: bug, Task, Individual Task: Mayur

#24 fix level control, checkpoint bug fixes, playercontroller additions
  Assets/PlayerController.cs
  Assets/Prefabs/PauseMenu.prefab
  Assets/Scenes/Level_1_Day.unity
  Assets/Scenes/Level_1_Night.unity
  Assets/Scenes/Level_2_Night.unity
  UserSettings/EditorUserSettings.asset
Labels: bug, Task, Individual Task: Mayur

#26 updated d7 version
  Assets/Scenes/Level_2_Night.unity
  UserSettings/EditorUserSettings.asset
Labels: Task, Individual Task: Mayur

#31 🍱 💄 (UI): Implemented Suggestions
  Assets/PauseMenuController.cs
  Assets/PlayBTN.cs
  Assets/PlayerController.cs
  Assets/Prefabs/PauseMenu.prefab
  Assets/Scenes/Level_1_Day.unity
  Assets/Scenes/MenuScene.unity
  Assets/Sound/mixkit-wood-hard-hit-2182-Edit1.wav
  Assets/Sound/mixkit-wood-hard-hit-2182-Edit1.wav.meta
  Assets/Sound/mixkit-wood-hard-hit-2182-Edit6.wav
  Assets/Sound/mixkit-wood-hard-hit-2182-Edit6.wav.meta
  UserSettings/EditorUserSettings.asset
Labels: bug, Task, Individual Task: Matthew

#45 control list + end cred mixer
  Assets/Prefabs/PauseMenu.prefab
  Assets/Scenes/End_Credits.unity
  UserSettings/EditorUserSettings.asset
Labels: Task, Individual Task: Mayur
